name: Acceptance Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  acceptance:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go test ./... -v -timeout 120m
        env:
          TF_ACC: "1"
          NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
